aws_region                      = "us-east-1"
project_name                    = "aws-web-platform"
environment                     = "dev"
owner                           = "platform-team"
cost_center                     = "engineering"
github_org                      = "cng13m"
github_repo                     = "AWSDevOpsAgent"
github_default_branch           = "main"
alarm_email                     = "shefkiu.genc@gmail.com"
image_tag                       = "latest"
vpc_cidr                        = "10.10.0.0/16"
azs                             = ["us-east-1a", "us-east-1b"]
public_subnet_cidrs             = ["10.10.0.0/24", "10.10.1.0/24"]
private_app_subnet_cidrs        = ["10.10.10.0/24", "10.10.11.0/24"]
private_data_subnet_cidrs       = ["10.10.20.0/24", "10.10.21.0/24"]
container_port                  = 8080
app_cpu                         = 256
app_memory                      = 512
desired_count                   = 1
min_capacity                    = 1
max_capacity                    = 2
health_check_path               = "/health"
db_name                         = "appdb"
db_username                     = "appuser"
db_instance_class               = "db.t4g.micro"
db_allocated_storage            = 20
db_max_allocated_storage        = 100
db_backup_retention_days        = 1
db_deletion_protection          = false
db_multi_az                     = false
db_performance_insights_enabled = false
db_monitoring_interval          = 0
log_retention_days              = 14
flow_log_retention_days         = 14
app_config = {
  "app/LOG_LEVEL"           = "info"
  "app/FEATURE_FLAG_SAMPLE" = "true"
}
