aws_region                      = "us-east-1"
project_name                    = "aws-web-platform"
environment                     = "prod"
owner                           = "platform-team"
cost_center                     = "engineering"
github_org                      = "cng13m"
github_repo                     = "AWSDevOpsAgent"
github_default_branch           = "main"
alarm_email                     = "shefkiu.genc@gmail.com"
image_tag                       = "latest"
vpc_cidr                        = "10.20.0.0/16"
azs                             = ["us-east-1a", "us-east-1b"]
public_subnet_cidrs             = ["10.20.0.0/24", "10.20.1.0/24"]
private_app_subnet_cidrs        = ["10.20.10.0/24", "10.20.11.0/24"]
private_data_subnet_cidrs       = ["10.20.20.0/24", "10.20.21.0/24"]
container_port                  = 8080
app_cpu                         = 512
app_memory                      = 1024
desired_count                   = 2
min_capacity                    = 2
max_capacity                    = 4
health_check_path               = "/health"
db_name                         = "appdb"
db_username                     = "appuser"
db_instance_class               = "db.t4g.small"
db_allocated_storage            = 20
db_max_allocated_storage        = 200
db_backup_retention_days        = 7
db_deletion_protection          = true
db_multi_az                     = true
db_performance_insights_enabled = true
db_monitoring_interval          = 60
log_retention_days              = 30
flow_log_retention_days         = 30
app_config = {
  "app/LOG_LEVEL"           = "info"
  "app/FEATURE_FLAG_SAMPLE" = "false"
}
